@Test_HostAddress = http://localhost:5104



POST {{Test_HostAddress}}/api/visits
Accept: application/json
Content-Type: application/json

{
  "visitId":  105,
  "clientId": 1,
  "mechanicLicenceNumber": "MECH-20230003",
  "services": [
    { "name": "Oil Change", "serviceFee": 79.50 }
  ]
}

###
